### ISSUE TITLE
Master to-do list

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#48]
- [x] Take a closer look at track with incorrect time (discard and replace with friend's track if need be) #41 
- [x] Exclude the 14-Aug-2019 data (except for the one known hunter) from the success analyses #46 
- [x] Calculate success rates of hunters BEFORE we filter out the unusable tracks (based purely on the metadata)
- [x] Assign states of "stationary on road" and "stationary off road" and redo cluster analysis #44
- [x] Calculate length of each behavioral bout, do some exploration of distributions of bout length across hunters #45
- [x] Examine success rate of different strategies as a function of hunting weekend / day #43
- [x] Calculate time-to-harvest (from start of hunt to harvest) for each successful hunter #42
- [x] Analysis of behavior and habitat in hour before hunt #39
- [x] Correlations between behaviors and habitat (rasters) #38
